# Generated by Django 4.0.1 on 2022-05-27 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gellery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10)),
                ('safety', models.CharField(max_length=27)),
                ('shah', models.CharField(max_length=50)),
                ('delivery', models.CharField(max_length=125)),
                ('AsiaPark', models.CharField(max_length=100)),
                ('Esen', models.TextField()),
                ('nav_2019', models.TextField()),
                ('HoReCa_2018', models.TextField()),
                ('Tengri_Music_2018', models.TextField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='food',
            options={'verbose_name_plural': 'Food'},
        ),
    ]
